apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-metrics-cronjob
  namespace: monitoring
spec:
  schedule: "* * * * *"  # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: collect-metrics
              image: pallavic9/metrics:v1.0.0
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: metrics-storage
                  mountPath: /metrics-output
          volumes:
            - name: metrics-storage
              persistentVolumeClaim:
                claimName: metrics-pvc
          restartPolicy: OnFailure
