apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-metrics-cronjob
  namespace: monitoring
spec:
  schedule: "* * * * *"  # Default: Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: collect-metrics
              image: metrics-task:v1.0.0
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: metrics-volume
                  mountPath: /metrics-output
          volumes:
            - name: metrics-volume
              emptyDir: {}
          restartPolicy: OnFailure
